
 import { Product } from "@/types/product";



const shopData: Product[] = [
  // ================= CHOCOLATE =================
  {
    id: 1,
    title: "Dubai Chocolate",
    category: "Chocolate",
    description:
      "Soft and moist chocolate cake, topped with delicious fruits, suiting every taste.",
    reviews: 0,
    gm: 1000,
    price: 125,
    discountedPrice: 125,
    imgs: { thumbnails: ["/images/product/dubaichocolate.jpg"], previews: ["/images/product/dubaichocolate.jpg"] },
  },
  {
    id: 2,
    title: "Drager Pecan Caramel",
    category: "Chocolate",
    description: "Premium pecan caramel chocolate.",
    reviews: 0,
    gm: 250,
    price: 85,
    discountedPrice: 85,
    imgs: { thumbnails: ["/images/product/dragerPecanCaramel.jpg"], previews: ["/images/product/dragerPecanCaramel.jpg"] },
  },
  {
    id: 3,
    title: "MADO Assorted Mix Chocolate Long Box",
    category: "Chocolate",
    description: "Assorted MADO chocolate mix in a long box.",
    reviews: 0,
    gm: 674,
    price: 240,
    discountedPrice: 240,
    imgs: { thumbnails: ["/images/product/madochocolat674.jpeg"], previews: ["/images/product/madochocolat674.jpeg"] },
  },
  {
    id: 4,
    title: "MADO Assorted Mix Chocolate Long Box",
    category: "Chocolate",
    description: "Assorted MADO chocolate mix in a long box.",
    reviews: 0,
    gm: 366,
    price: 135,
    discountedPrice: 135,
    imgs: { thumbnails: ["/images/product/madochocolat366.jpg"], previews: ["/images/product/madochocolat366.jpg"] },
  },

  // ================= DATES =================
  {
    id: 5,
    title: "MADO Stuffed Dates Majdool",
    category: "Stuffed Dates",
    description: "Premium Majdool dates stuffed with rich fillings.",
    reviews: 0,
    gm: 800,
    price: 160,
    discountedPrice: 160,
    imgs: { thumbnails: ["/images/product/stuffedDatesMajdool.jpeg"], previews: ["/images/product/stuffedDatesMajdool.jpeg"] },
  },
  {
    id: 6,
    title: "MADO Pre Packed Dates Majdool Super Jumbo",
    category: "Dates",
    description: "Pre-packed Majdool super jumbo dates.",
    reviews: 0,
    gm: 900,
    price: 140,
    discountedPrice: 140,
    imgs: { thumbnails: ["/images/product/mADOPrePacked.jpg"], previews: ["/images/product/mADOPrePacked.jpg"] },
  },
  {
    id: 7,
    title: "MADO Dates Majdool Super Jumbo",
    category: "Dates",
    description: "Premium Majdool super jumbo dates.",
    reviews: 0,
    gm: 250,
    price: 38,
    discountedPrice: 38,
    imgs: { thumbnails: ["/images/product/datesmajdoolsuperjumbo.jpg"], previews: ["/images/product/datesmajdoolsuperjumbo.jpg"] },
  },

  // ================= STUFFED DATES =================
  {
    id: 8,
    title: "Stuffed Dates Jumbo Hazelnut",
    category: "Stuffed Dates",
    description: "Jumbo stuffed Majdool dates filled with hazelnut.",
    reviews: 0,
    gm: 250,
    price: 50,
    discountedPrice: 50,
    imgs: { thumbnails: ["/images/product/stuffeddatesjumbohazelnut.jpg"], previews: ["/images/product/stuffeddatesjumbohazelnut.jpg"] },
  },
  {
    id: 9,
    title: "Stuffed Dates Jumbo Walnut",
    category: "Stuffed Dates",
    description: "Jumbo stuffed Majdool dates filled with walnut.",
    reviews: 0,
    gm: 250,
    price: 50,
    discountedPrice: 50,
    imgs: { thumbnails: ["/images/product/stuffeddatesjumbowalnut.jpg"], previews: ["/images/product/stuffeddatesjumbowalnut.jpg"] },
  },
  {
    id: 10,
    title: "Stuffed Dates Jumbo Macadamia",
    category: "Stuffed Dates",
    description: "Jumbo stuffed Majdool dates filled with macadamia.",
    reviews: 0,
    gm: 250,
    price: 50,
    discountedPrice: 50,
    imgs: { thumbnails: ["/images/product/stuffeddatesjumbomecademia.jpg"], previews: ["/images/product/stuffeddatesjumbomecademia.jpg"] },
  },
  {
    id: 11,
    title: "Stuffed Dates Jumbo Pomegranate",
    category: "Stuffed Dates",
    description: "Jumbo stuffed Majdool dates with pomegranate flavor.",
    reviews: 0,
    gm: 250,
    price: 50,
    discountedPrice: 50,
    imgs: { thumbnails: ["/images/product/stuffeddatesjumbopomegaranate.jpg"], previews: ["/images/product/stuffeddatesjumbopomegaranate.jpg"] },
  },
  {
    id: 12,
    title: "Stuffed Dates Jumbo Pistachio",
    category: "Stuffed Dates",
    description: "Jumbo stuffed dates filled with pistachio.",
    reviews: 0,
    gm: 250,
    price: 50,
    discountedPrice: 50,
    imgs: { thumbnails: ["/images/product/stuffeddatesjumbopistachio.jpg"], previews: ["/images/product/stuffeddatesjumbopistachio.jpg"] },
  },
  {
    id: 13,
    title: "Stuffed Dates Jumbo Cashew",
    category: "Stuffed Dates",
    description: "Jumbo stuffed dates filled with cashew.",
    reviews: 0,
    gm: 250,
    price: 50,
    discountedPrice: 50,
    imgs: { thumbnails: ["/images/product/stuffedcashew.jpg"], previews: ["/images/product/stuffedcashew.jpg"] },
  },
  {
    id: 14,
    title: "Stuffed Dates Jumbo Pecan",
    category: "Stuffed Dates",
    description: "Jumbo stuffed dates filled with pecan.",
    reviews: 0,
    gm: 250,
    price: 50,
    discountedPrice: 50,
    imgs: { thumbnails: ["/images/product/stuffeddatesjumbopecan.jpg"], previews: ["/images/product/stuffeddatesjumbopecan.jpg"] },
  },
  {
    id: 15,
    title: "Stuffed Dates Jumbo Almond",
    category: "Stuffed Dates",
    description: "Jumbo stuffed dates filled with almond.",
    reviews: 0,
    gm: 250,
    price: 50,
    discountedPrice: 50,
    imgs: { thumbnails: ["/images/product/stuffeddatesjumboalmond.jpg"], previews: ["/images/product/stuffeddatesjumboalmond.jpg"] },
  },

  // ================= SPECIAL DATES =================
  {
    id: 16,
    title: "MADO Dates Sukkari",
    category: "Dates",
    description: "Sweet and soft premium Sukkari dates.",
    reviews: 0,
    gm: 250,
    price: 28,
    discountedPrice: 28,
    imgs: { thumbnails: ["/images/product/datessukkari.jpg"], previews: ["/images/product/datessukkari.jpg"] },
  },
  {
    id: 17,
    title: "MADO Dates Sagee",
    category: "Dates",
    description: "High quality Sagee dates.",
    reviews: 0,
    gm: 250,
    price: 28,
    discountedPrice: 28,
    imgs: { thumbnails: ["/images/product/datessagee.jpg"], previews: ["/images/product/datessagee.jpg"] },
  },
  {
    id: 18,
    title: "MADO Dates Ajwat",
    category: "Dates",
    description: "Premium Ajwat dates with rich flavor.",
    reviews: 0,
    gm: 250,
    price: 43,
    discountedPrice: 43,
    imgs: { thumbnails: ["/images/product/datesajwat.jpg"], previews: ["/images/product/datesajwat.jpg"] },
  },
  {
    id: 19,
    title: "MADO Dates Khudri",
    category: "Dates",
    description: "Classic Khudri dates with firm texture.",
    reviews: 0,
    gm: 250,
    price: 28,
    discountedPrice: 28,
    imgs: { thumbnails: ["/images/product/dateskhudri.jpg"], previews: ["/images/product/dateskhudri.jpg"] },
  },

  // ================= SWEETS =================
  {
    id: 20,
    title: "Turkish Baklawa",
    category: "Sweets",
    description: "Classic Turkish baklawa with pistachio, walnut and cashew.",
    reviews: 0,
    gm: 1000,
    price: 300,
    discountedPrice: 300,
    imgs: { thumbnails: ["/images/product/turkishbaklava.jpeg"], previews: ["/images/product/turkishbaklava.jpeg"] },
  },
  {
    id: 21,
    title: "Assorted Baklawa 500gm",
    category: "Sweets",
    description: "Assorted baklawa selection with pistachio and walnut.",
    reviews: 0,
    gm: 500,
    price: 125,
    discountedPrice: 125,
    imgs: { thumbnails: ["/images/product/assortedbaklava500gm.jpg"], previews: ["/images/product/assortedbaklava500gm.jpg"] },
  },
  {
    id: 22,
    title: "Assorted Baklawa 250gm",
    category: "Sweets",
    description: "Assorted baklawa selection with pistachio and walnut.",
    reviews: 0,
    gm: 250,
    price: 65,
    discountedPrice: 65,
    imgs: { thumbnails: ["/images/product/assortedbaklava250gm1.jpg","/images/product/assortedbaklava250gm2.jpg"], previews: ["/images/product/assortedbaklava250gm1.jpg","/images/product/assortedbaklava250gm2.jpg"] },
  },
  {
    id: 23,
    title: "Barazik",
    category: "Sweets",
    description: "Traditional sesame barazik sweets.",
    reviews: 0,
    gm: 550,
    price: 90,
    discountedPrice: 90,
    imgs: { thumbnails: ["/images/product/barazik-550gm.jpg","/images/product/barazik-550gm2.jpg"], previews: ["/images/product/barazik-550gm.jpg","/images/product/barazik-550gm2.jpg"] },
  },

  // ================= NUTS =================
  {
    id: 24,
    title: "Healthy Raw Nuts",
    category: "Nuts",
    description: "Natural and nutritious selection of raw nuts.",
    reviews: 0,
    gm: 1000,
    price: 85,
    discountedPrice: 85,
    imgs: { thumbnails: ["/images/product/energy-mix-nuts-fruits.jpg"], previews: ["/images/product/energy-mix-nuts-fruits.jpg"] },
  },
  {
    id: 25,
    title: "Premium Mix Nuts",
    category: "Nuts",
    description: "Luxury mix of cashews, almonds, pistachios and macadamia.",
    reviews: 0,
    gm: 1000,
    price: 75,
    discountedPrice: 75,
    imgs: { thumbnails: ["/images/product/mixednutspriemium.png"], previews: ["/images/product/mixednutspriemium.png"] },
  },
  {
    id: 26,
    title: "Mix Nuts",
    category: "Nuts",
    description: "Blend of nuts, seeds, peas, chickpeas and roasted corn.",
    reviews: 0,
    gm: 1000,
    price: 60,
    discountedPrice: 60,
    imgs: { thumbnails: ["/images/product/mixxnuts.png"], previews: ["/images/product/mixxnuts.png"] },
  },

  // ================= COOKIES =================
  {
    id: 27,
    title: "MADO Cookies Black & White",
    category: "Cookies",
    description: "Classic black and white MADO cookies.",
    reviews: 0,
    gm: 0,
    price: 15,
    discountedPrice: 15,
    imgs: { thumbnails: ["/images/product/coockies1.png"], previews: ["/images/product/coockies1.png"] },
  },
  {
    id: 28,
    title: "MADO Cookies Salted Nutella",
    category: "Cookies",
    description: "Salted Nutella flavored MADO cookies.",
    reviews: 0,
    gm: 0,
    price: 15,
    discountedPrice: 15,
    imgs: { thumbnails: ["/images/product/coockies2.png"], previews: ["/images/product/coockies2.png"] },
  },
  {
    id: 29,
    title: "MADO Cookies Original",
    category: "Cookies",
    description: "The original classic MADO cookie.",
    reviews: 0,
    gm: 0,
    price: 15,
    discountedPrice: 15,
    imgs: { thumbnails: ["/images/product/coockies3.png"], previews: ["/images/product/coockies3.png"] },
  },
  {
    id: 30,
    title: "MADO Cookies Double Chocolate",
    category: "Cookies",
    description: "Rich double chocolate MADO cookies.",
    reviews: 0,
    gm: 0,
    price: 15,
    discountedPrice: 15,
    imgs: { thumbnails: ["/images/product/coockies4.png"], previews: ["/images/product/coockies4.png"] },
  },
];

export default shopData;
